# ----------------------------------------------------------------------
# |
# |  manual_validate_with_dependencies.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-03-21 19:27:28
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate (including dependencies)"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  _c7849079-99f5-40ae-b31d-47b704ec5365:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_MiscScriptsMixin/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}
      bootstrap_branch_overrides: "v4-DavidBrownell_MiscScriptsMixin:${{ inputs.repo_branch }}"
