# ----------------------------------------------------------------------
# |
# |  manual_validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-03-21 19:27:37
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      force_setup:                          {type: boolean, required: false, default: false, description: "Apply the '--force' flag during setup activities."}
      force_activate:                       {type: boolean, required: false, default: false, description: "Apply the '--force' flag during activation activities."}
      no_cache:                             {type: boolean, required: false, default: false, description: "Do not use the GitHub action cache for this build."}

jobs:
  _5b1a9dda-69f2-4ddc-a2c6-87f53f2bc095:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_MiscScriptsMixin/.github/workflows/validate.yaml@CI-v1
    with:
      repo_branch: ${{ github.ref_name }}

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}
