# ----------------------------------------------------------------------
# |
# |  validate_with_dependencies.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-03-21 19:27:59
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[callable] Validates v4-DavidBrownell_MiscScriptsMixin (and its dependencies)"

on:
  workflow_call:
    inputs:
      repo_branch:                          {type: string, required: true}

jobs:
  _c7f6736f-d26a-4c42-ad34-44057d7f8adb:
    name: "v4-DavidBrownell_MiscScriptsMixin"
    uses: davidbrownell/v4-DavidBrownell_MiscScriptsMixin/.github/workflows/validate.yaml@CI-latest
    with:
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: "v4-DavidBrownell_MiscScriptsMixin:${{ inputs.repo_branch }}"
